### ISSUE TITLE
Need docs

### ISSUE THREAD

**Issue by asklar** [microsoft/winmd#10]
It would be great to have docs on how to use this library. Some things I've noticed that weren't obvious to me as a first time user of  the library:

1. things that return `std::pair<T, T>` like `db.PropertyList()` as a way to enable range-based loops. This is cool but non-obvious, we should document it
2. Getting enum values from an enum isn't super obvious (there is a get_enumerator if you follow the intellisense but that's not the right thing to use). Also, you need to make sure you are getting the constant value based on the right underlying type (int vs. uint). This can be determined based on `value.Signature().Type().element_type() == ElementType::U4` for WinRT
3. Some entries don't behave gracefully and crash or throw if you call APIs on them, e.g. the <Module> type crashes when doing `is_enum` on it. These can be filtered out based on e.g. `SpecialName()`
4. Hard to figure out if something is a struct or not.
5. Guidance on should I use the db or the cache?

(lots more to come :) )

**Comment by kennykerr** [comment]
We have no plans to document the winmd parser at this time, but feel free to contribute something.

**Comment by asklar** [comment]
@kennykerr I filed these things after talking to @DefaultRyan , I was under the impression he was going to document these?

**Comment by kennykerr** [comment]
Feel free to reopen if you or Ryan would like to take a stab at documenting this library, but realistically our team is rather swamped and this isn't on the list of things we plan to tackle.
