### ISSUE TITLE
impl/base.h is not namespaced

### ISSUE THREAD

**Issue by dlech** [microsoft/winmd#25]
When you add the winmd package to your include directories and your project already contains it's own "impl/base.h" header file, it causes problems. 

This could be solved by moving everything in `impl` up a directory level and removing the `impl` folder and renaming `base.h` to `winmd_base.h`.

**Comment by kennykerr** [comment]
Note that this winmd parser is no longer under active development and mostly serves as an implementation detail of https://github.com/microsoft/cppwinrt so I'm reluctant to make any significant changes at this point.
