### ISSUE TITLE
Error messages regarding unresolved typeref for custom attribute params doesn't include the details of the type

### ISSUE THREAD

**Issue by smaillet-ms** [microsoft/winmd#26]
https://github.com/microsoft/winmd/blob/ab1436427ede293ddad944d3688e83b3fba3a173/src/impl/winmd_reader/custom_attribute.h#L313

This is a simple string that says "something" went wrong and I'm not gonna tell ya. Na na nan na nana!

This sort of thing is frustrating for a user as they have no clue what it is referring to. All the information should be there in the code to form a much better message that includes the FQN for the unresolved type, it should also have the module reference to identify what module the type is supposed to come from. This would make resolving such errors WAY easier.

**Comment by kennykerr** [comment]
Note that this winmd parser is no longer under active development and mostly serves as an implementation detail of https://github.com/microsoft/cppwinrt but feel free to contribute such an improvement.
