### ISSUE TITLE
view.h uses std::exchange but <utility> not included

### ISSUE THREAD

**Issue by alvinhochun** [microsoft/winmd#27]
`impl/winmd_reader/view.h` uses `std::exchange` but `<utility>` has not been explicitly included. It fails to build on GCC 12 / libstdc++ with `error: 'exchange' is not a member of 'std'`.

**Comment by kennykerr** [comment]
Feel free to contribute a fix, although this library doesn't get updated often so it may not be worth the effort when the workaround is pretty simple.

**Comment by alvinhochun** [comment]
> it may not be worth the effort when the workaround is pretty simple.

I agree, and it's already handled in cppwinrt.
