### ISSUE TITLE
 if (*(view.data() + view.size())) is UB

### ISSUE THREAD

**Issue by expnkx** [microsoft/winmd#8]
https://github.com/microsoft/winmd/blob/1b97d886b38135b892880566f2cfaee31cd668a1/src/impl/base.h#L59

Doing this the OS might swap clean pages to treat it and then causes a serious vuln.

basic_string_view should only be dealt with contract not doing this runtime check

**Comment by DefaultRyan** [comment]
Agreed, this looks like a problem.

**Comment by kennykerr** [comment]
Agreed the check isn't very helpful. In practice, this is only used with null terminated strings so it's probably benign. Feel free to contribute a change that removes the `c_str` function. It's not that critical to the library.
